### ISSUE TITLE
java formatter 도입

### ISSUE THREAD

**Issue by Gwo-O9** [snuhcs-course/swpp-2023-project-team-12#18]
google_checkstyle 지금 그대로 도입 시 감당이 안될 정도로 많은 수정 사항이 생김

대안은
1. google_checkstyle 파일 수정 후 사용
2. 다른 formatter 도입 검토
3. 도입하지 않음

**Comment by tangamzaa** [comment]
iter 3 회의에 넣어 놓겠습니다!

**Comment by Gwo-O9** [comment]
도입하지 않기로 함
