### ISSUE TITLE
멀티모드 네비게이션 버튼이 동작하지 않는 문제

### ISSUE THREAD

**Issue by Gwo-O9** [snuhcs-course/swpp-2023-project-team-12#19]
방만든 상태로 클릭하면 넘어는 가는데 네비게이션 바 상태가 변하지 않음

<img width="333" alt="스크린샷 2023-10-17 오후 1 45 44" src="https://github.com/snuhcs-course/swpp-2023-project-team-12/assets/101039305/135bf46a-ca6f-4842-a4a7-61943be62973">

**Comment by tangamzaa** [comment]
(1) 해결되었습니다!
(2) 그런데 방을 만든 상태에서는 어디 안 나가는 게 더 좋지 않나 생각이 드는데 iter 3 논의 주제 중 하나로 남겨놓으면 좋을 것 같아요!
