### ISSUE TITLE
[멀티모드] 멀티모드 다른 앱 사용 중 게임 시작하면 대기중 화면에서 멈추는 문제

### ISSUE THREAD

**Issue by Gwo-O9** [snuhcs-course/swpp-2023-project-team-12#64]
시간이 되어 경기 시작되었을 때 다시 앱을 실행하면 방 대기중화면에서 넘어가지 못하고 있음

**Comment by SNURO** [comment]
11/16일부로 게임이 시작되고 직무유기한 방장은 강제퇴장처리 되기는 하는데, 게임이 제대로 시작되는건 확인했으나 제대로 끝나는것 같아 보이지는 않음

**Comment by SNURO** [comment]
게임 시작 5분전, 1분전 알림이라도 보내줍시다

**Comment by Gwo-O9** [comment]
resloved by #78
