### ISSUE TITLE
[로그인/로그아웃] 동일 기기에서 로그인/로그아웃 반복할 시 간헐적으로 문제발생

### ISSUE THREAD

**Issue by SNURO** [snuhcs-course/swpp-2023-project-team-12#73]
![image](https://github.com/snuhcs-course/swpp-2023-project-team-12/assets/110530065/a8655f15-e93a-473d-8c7c-741e7fa124d4)

(동일한 ip주소를 향해) 프로세스가 계속해서 쌓이다가 어느순간부터 로그인 불가 현상

**Comment by Gwo-O9** [comment]
#80
